### ISSUE TITLE
Error "Parameter bufferSize given invalid value NaN."

### ISSUE THREAD

**Issue by palicand** [saurfang/spark-knn#8]
Hello. I'm almost constantly getting the error "Parameter bufferSize given invalid value NaN." while training the KNN model. I suspect this might be caused by me incorrectly setting the `setBufferSizeSampleSizes`, although I have no idea what should be the correct values there. My dataset has about 3800 data points (it is a dataset that's supposed to be used only for testing). I'm trying various ranges, with big or small values, but none helps. Is there any guideline on how many and how big those samples should be? For now I am setting the bufferSize manually, instead of having it estimated.

Thanks!

**Comment by saurfang** [comment]
hmm. Any chance your point value might have NaNs? I don't remember I have tested this with data with nulls or NaNs. Maybe you can try filter them out?

**Comment by palicand** [comment]
I'm quite sure they do not have NaNs, but I'll check just to be sure.

**Comment by Im0rtality** [comment]
Having same issue. `math.sqrt(-1 / beta)` returns NaN because beta is positive.

```
rs: 0.00732488804495208
beta: 0.00732488804495208
```

Too lazy to copy paste all variables so here's screenshot
<img width="885" alt="screenshot 2016-05-11 14 38 26" src="https://cloud.githubusercontent.com/assets/1804210/15179697/23fdb0f8-1786-11e6-984f-890f4387f0c7.png">

**Comment by ChrisYohann** [comment]
Having those issues too.

At the beginning, tau was NaN because of stdDevs for x and y were 0.
I figured out that with my dataset of only 100 points, the default sampleSize boundaries were too high, causing x and y vectors of 1 (or 2) dimensions. So i wrote this piece of code to avoid it.

def setSamplesSizesKNN(dataset : DataFrame):Array[Int] ={
    val count = dataset.count.toDouble
    (0 to 1.0*count by count*0.1).toArray.map(x => x.toInt)
}

But it seems that tau is still NaN because of beta being positive. 
Replacing by math.sqrt(math.abs(1/beta)) might fix it.

**Comment by saurfang** [comment]
Thanks all for the information. I just pushed a change that in the case beta is positive, we fall back on some other heuristic guess. Although if your dataset will stay small, I suggest you set balance threshold to 0 and only use metric tree for better accuracy (e.g. https://github.com/saurfang/spark-knn/blob/master/spark-knn-core/src/test/scala/org/apache/spark/ml/knn/KNNSuite.scala#L128). Can you give it a try and let me know if it helps?

**Comment by ChrisYohann** [comment]
Sorry for not having answered sooner. I try you new piece of code and yes, it works fine now.
Also switching to full metric tree by setting balanceThreshold to zero.

Just one more thing about this piece of code :
val tau =
      if ($(balanceThreshold) > 0 && $(bufferSize) < 0) {
        KNN.estimateTau(data, $(bufferSizeSampleSizes), rand.nextLong())
      } else {
        $(bufferSize)
      }

$(bufferSize) is set to -1.0 by Default. If you forget to set it to 0.0 on metric tree, you end up with "Indices must be non-empty" error. 

Thanks for all.

**Comment by saurfang** [comment]
Can you give me the stacktrace for the "Indices must be non-empty" error please? I don't feel like this should happen.

**Comment by ChrisYohann** [comment]
I don't know if you will be able to see something with Spark stacktrace but here it is.

org.apache.spark.SparkException: Job aborted due to stage failure: Task 4 in stage 167.0 failed 4 times, most recent failure: Lost task 4.3 in stage 167.0 (TID 18522, xxxxxxxxxxx): java.lang.AssertionError: assertion failed: indices must be non-empty: [##My Indices##] (0) at scala.Predef$.assert(Predef.scala:179) at org.apache.spark.ml.knn.KNNModelParams$$anonfun$2.apply(KNN.scala:86) at org.apache.spark.ml.knn.KNNModelParams$$anonfun$2.apply(KNN.scala:80) at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371) at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:126) at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73) at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41) at org.apache.spark.scheduler.Task.run(Task.scala:89) at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at java.lang.Thread.run(Thread.java:745)

To be more precise, in the function searchIndecies(v: VectorWithNorm, tree: Tree, tau: Double, acc: Int = 0)

when you check :
val buffer = new ArrayBuffer[Int]
        if (leftDistance - rightDistance <= tau) {
          buffer ++= searchIndecies(v, node.leftChild, tau, acc)
        }

        if (rightDistance - leftDistance <= tau) {
          buffer ++= searchIndecies(v, node.rightChild, tau, acc + node.leftChild.leafCount)
        }

        buffer

if tau is not unchanged (for example when you set balanceThreshold to zero), you have tau that equals -1, and then the if conditions become : 
if (rightDistance - leftDistance <= -1)
if(leftDistance - rightDistance <= -1) which can be both false, (particulary in my case where I have scaled the data) and giving this result.

Hope that it helps.

**Comment by saurfang** [comment]
I see. You're right. Fixed in https://github.com/saurfang/spark-knn/commit/dd741ec9f10e6d6247bfaba22d981e5513db08c5. Thanks!
